### ISSUE TITLE
Compile for macOS, Linux and Windows and pack compiled versions

### ISSUE THREAD

**Issue by konard** [robertvazan/crc32c-hw#6]
Hello @robertvazan,

In order to [add support for .NET Standard for crc32c.net](https://github.com/robertvazan/crc32c.net/issues/1) we have to build and pack the binaries.

We can use GitHub Actions to build on all these platforms.

So looks like we have to add second package into the repository with a different name to contain binaries only version of the package.

What do you think?

**Comment by robertvazan** [comment]
And Crc32C.NET would then depend on those prebuilt binaries? Perhaps conditionally depending on platform? Is this how other projects do it? Is there a tutorial somewhere on how to do it? In any case, if you would like to give it a try, I am happy to assist you.

**Comment by konard** [comment]
Yes, other project do something like this. I also did it for my project.
For example this .NET Standard package - https://www.nuget.org/packages/Platform.Data.Triplets uses the binaries package https://www.nuget.org/packages/Platform.Data.Triplets.Kernel.
I did it based on how SQLite packages were built:
https://www.nuget.org/packages/SQLitePCLRaw.bundle_e_sqlite3 and https://www.nuget.org/packages/SQLitePCLRaw.lib.e_sqlite3.
I used https://github.com/NuGetPackageExplorer to open packages directly to analyse how they were built.

**Comment by robertvazan** [comment]
This library is no longer maintained. Feed free to adopt it if you find it useful.
